### PR TITLE
Namespaced xml

### PR DESCRIPTION
**Pull request by TommasoPino**
I prepared this modification in order to handle the reading of an OEM file in XML format that has a namespace in it. The modification will remove from the tag the namespace, it is transparent for XML files without namespace.

### CODE REVIEW

**Comment by bradsease** [comment]
Apologies for losing track of this -- I think I understand now. If you revert the changes to setup.py I can merge this in.

**Comment by TommasoPino** [comment]
Hello @bradsease. As asked, I reverted the setup.py file.
Have a nice day.

**Comment by TommasoPino** [comment]
Just a question, I encountered a problem installing the package directly from the repository due to the setup.py line you asked me to revert. It is possible to generalize the setup.py to avoid this problem. A "setup.cfg" could be useful in that sense

**Comment by bradsease** [comment]
Sorry about that -- I'll work on making that more general. I was focused on getting it to work with my CI/CD and didn't think about local use.

**Pull request merged**
